const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const assignSchema = mongoose.Schema(
    {
        client:{
            type:String,
            require:true
        },
        phone:Number,
        dob:Date,
        ssn:String,
        age:Number,
        race:String,
        sex:String,
        emergencyContact:Number,
        responsibleParty:{
            name:String,
            phone:Number
        },
        advanceDirective:Boolean,
        copyOnFile:Boolean,
        dnr:Boolean,
        poa:{
            name:String,
            primaryLanguage:String
        },
        cultural:String,
        healthAssessment:{
            admittedFrom:String,
            allergies:String,
            diagnosis:String,
            healthProblems:String,
            reasonForAdnission:String,
            housing:String,
            hospitalStay:String,
            medications:String,
            comments:String
        },
        vitalSigns:{
            bp:String,
            pulse:Number,
            respiration:Number,
            temperature:Number,
            height:Number,
            weight:Number,   
        },
        pains:{
            intensity:Number,
            location:String,
            duration:String,
            controlled:Boolean,
            comments:String
        },
        heents:{
            eyes:{
                impairedVision:Boolean,
                cataracts:Boolean,
                retinopathy:Boolean,
                blind:Boolean
            },
            nose:{
                discharge:Boolean,
                bleeding:Boolean,
                congested:Boolean
            },
            oral:{
                sores:Boolean,
                gingivitis:Boolean,
                stomatitis:Boolean
            },
            throat:{
                hoarse:Boolean,
                dysphasia:Boolean
            },
            ears:{
                tinnitus:Boolean,
                pain:Boolean,
                hoh:Boolean,
                comments:String
            }
        },
        neurological:{
            cva:Boolean,
            weakness:Boolean,
            generalized:Boolean,
            profound:Boolean,
            vertigo:Boolean,
            headache:Boolean,
            tremors:Boolean,
            paralysis:Boolean,
            numbness:Boolean,
            tingling:Boolean,
            itching:Boolean,
            burning:Boolean,
            syncope:Boolean,
            ataxia:Boolean,
            seizures:Boolean,
            perrla:Boolean,
            sensesIntact:Boolean,
            comments:String
        },
        cardiovascular:{
            chestPain:Boolean,
            palpitations:Boolean,
            jvd:Boolean,
            pvd:Boolean,
            vertigo:Boolean,
            pulseDeficit:Boolean,
            edema:String,
            peripheralPulses:Boolean,
            cyanosis:Boolean,
            murmur:Boolean,
            varicoseVeins:Boolean,
            claudication:Boolean,
            pacemakerSetting:String,
            dateChecked:Date,
            numbness:Boolean,
            tingling:Boolean,
            fatigue:Boolean,
            comments:String
        },
        gastrointestinal:{
            heartburn:Boolean,
            distention:Boolean,
            flatulence:Boolean,
            cramping:Boolean,
            ascites:Boolean,
            nausea:Boolean,
            vomiting:Boolean,
            constipation:Boolean,
            bleeding:Boolean,
            incontinence:Boolean,
            anorexia:Boolean,
            dysphagia:Boolean,
            diarrhea:Boolean,
            bowelSounds:String,
            ostomy:String,
            ngTube:Boolean,
            gastricTube:Boolean,
            jejunostomyTube:Boolean,
            comments:String
        },
        gyn:{
            frequency:Boolean,
            urgency:Boolean,
            nocturia:Boolean,
            pain:Boolean,
            burning:Boolean,
            hematuria:Boolean,
            odor:Boolean,
            retention:Boolean,
            polyuria:Boolean,
            dysuria:Boolean,
            incontinence:Boolean,
            ostomy:Boolean,
            catheter:{
                condom:Boolean,
                indwelling:Boolean,
                suprapubic:Boolean
            },
            vaginalBleeding:Boolean,
            discharge:Boolean,
            comments:String
        },
        skin:{
            color:{
                pink:Boolean,
                pale:Boolean,
                cyanotic:Boolean,
                jaundiced:Boolean
            },
            temperature:{
                hot:Boolean,
                warm:Boolean,
                cool:Boolean
            },
            turgor:{
                supple:Boolean,
                sluggish:Boolean,
                tenting:Boolean
            },
            condition:{
                dry:Boolean,
                moist:Boolean,
                diaphoretic:Boolean,
                rash:Boolean,
                ecchymosis:Boolean,
                petechiae:Boolean,
                comments:String
            }
        },
        wound:{
            location:String,
            stage:String,
            length:Number,
            width:Number,
            depth:Number,
            drainage:String,
            tunneling:Boolean,
            odor:String,
            surroundingTissue:String,
            edema:Boolean
        },
        respiratory:{
            lungAuscultation:{
                clear:Boolean,
                left:Boolean,
                right:Boolean
            },
            capillaryNailRefill:String,
            dyspnea:Boolean,
            exertion:Boolean,
            orthopnea:Boolean,
            cough:Boolean,
            labored:Boolean,
            hemoptysis:Boolean,
            sputum:{
                color:String,
                amount:Number
            },
            oxygenLiterFlow:Number,
            cont:Boolean,
            prn:Boolean,
            concentrator:Boolean,
            tank:Boolean,
            portable:Boolean,
            nc:Boolean,
            asymmetric:Boolean,
            barrelChest:Boolean,
            apnea:Boolean,
            shallow:Boolean,
            comments:String
        },
        tracheostomy:String,
        ventilator:String,
        nebulizerTx:String,
        med:String,
        comments:String,
        mentalStatus:{
            oriented:Boolean,
            forgetful:Boolean,
            disoriented:Boolean,
            agitated:Boolean,
            depressed:Boolean,
            lethargic:Boolean,
            alert:Boolean,
            other:Boolean
        },
        adls:{
            bathing:Boolean,
            dressing:Boolean,
            feeding:Boolean,
            toileting:Boolean,
            transferring:Boolean,
            ambulation:Boolean,
            dietaryRequirements:String
        },
        instrumentalAdls:{
            canTakeMeds:Boolean,
            ableToShop:Boolean,
            canPrepmeals:Boolean,
            useTelephone:Boolean,
            canDoHousework:Boolean,
            canShop:Boolean,
            managersOwnFinances:Boolean
        },
        specialEquipment:{
            hospBed:Boolean,
            regularBed:Boolean,
            commods:Boolean,
            toiletExt:Boolean,
            oxygen:Boolean,
            wheelchair:Boolean,
            walker:Boolean,
            cane:Boolean,
            lift:Boolean,
            grabBars:Boolean,
            nebulizer:Boolean,
            gaitBelt:Boolean,
            cpap:Boolean,
            other:Boolean
        },
        safetyMeasures:{
            cardiacPrec:Boolean,
            diabeticPrec:Boolean,
            htnPrec:Boolean,
            oxygenPrec:Boolean,
            pulmPrec:Boolean,
            preventFalls:Boolean,
            psychPrec:Boolean,
            maintainSafeEnvironment:Boolean,
            other:Boolean
        },
        functionalLimitations:{
            amputation:Boolean,
            bladder:Boolean,
            legallyBlind:Boolean,
            paralysis:Boolean,
            endurance:Boolean,
            hearing:Boolean,
            speech:Boolean,
            contracture:Boolean,
            minorExertion:Boolean
        },
        mobility:{
            compBedrest:Boolean,
            upAsTolerated:Boolean,
            partWtBearing:Boolean,
            independent:Boolean,
            transfer:Boolean,
            wheelchair:Boolean,
            walker:Boolean,
            cane:Boolean,
            crutches:Boolean,
            exercise:Boolean,
            other:Boolean
        },
        socialActivities:String,
        prognosis:{
            poor:Boolean,
            guarded:Boolean,
            fair:Boolean,
            good:Boolean,
            excellent:Boolean
        },
        otherComments:String,
        infectionControl:String,
        date:Date,
        rnSignature:String

    },
    {
        timestamps: true
    }
);

module.exports = mongoose.model('Assign', assignSchema);